# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      #   - link: "mysql:root:root@tcp(127.0.0.1:3306)/ai_system"
      #     tables: "intelligent_merchant"
      #     jsonCase: "CamelLower"
      #     removePrefix: "intelligent_"
      #     group: "ai"
      #     descriptionTag: true

      - link: "mysql:root:@tcp(127.0.0.1:3306)/gf"
        tables: "game_bingo_bet_types,game_bingo_dynamic_odds,game_bingo_draws,game_bingo_bets"
        jsonCase: "CamelLower"
        removePrefix: "game_"
        group: "default"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
