// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// adminDao is the data access object for the table game_admin.
// You can define custom methods on it to extend its functionality as needed.
type adminDao struct {
	*internal.AdminDao
}

var (
	// Admin is a globally accessible object for table game_admin operations.
	Admin = adminDao{internal.NewAdminDao()}
)

// Add your custom methods and functionality below.
