// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// bingoBetsDao is the data access object for the table game_bingo_bets.
// You can define custom methods on it to extend its functionality as needed.
type bingoBetsDao struct {
	*internal.BingoBetsDao
}

var (
	// BingoBets is a globally accessible object for table game_bingo_bets operations.
	BingoBets = bingoBetsDao{internal.NewBingoBetsDao()}
)

// Add your custom methods and functionality below.
