// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// bingoBetTypesDao is the data access object for the table game_bingo_bet_types.
// You can define custom methods on it to extend its functionality as needed.
type bingoBetTypesDao struct {
	*internal.BingoBetTypesDao
}

var (
	// BingoBetTypes is a globally accessible object for table game_bingo_bet_types operations.
	BingoBetTypes = bingoBetTypesDao{internal.NewBingoBetTypesDao()}
)

// Add your custom methods and functionality below.
