// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// bingo28DynamicOddsDao is the data access object for the table game_bingo28_dynamic_odds.
// You can define custom methods on it to extend its functionality as needed.
type bingo28DynamicOddsDao struct {
	*internal.Bingo28DynamicOddsDao
}

var (
	// Bingo28DynamicOdds is a globally accessible object for table game_bingo28_dynamic_odds operations.
	Bingo28DynamicOdds = bingo28DynamicOddsDao{internal.NewBingo28DynamicOddsDao()}
)

// Add your custom methods and functionality below.
