// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// bingo28BetsDao is the data access object for the table game_bingo28_bets.
// You can define custom methods on it to extend its functionality as needed.
type bingo28BetsDao struct {
	*internal.Bingo28BetsDao
}

var (
	// Bingo28Bets is a globally accessible object for table game_bingo28_bets operations.
	Bingo28Bets = bingo28BetsDao{internal.NewBingo28BetsDao()}
)

// Add your custom methods and functionality below.
