// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// bingo28DrawsDao is the data access object for the table game_bingo28_draws.
// You can define custom methods on it to extend its functionality as needed.
type bingo28DrawsDao struct {
	*internal.Bingo28DrawsDao
}

var (
	// Bingo28Draws is a globally accessible object for table game_bingo28_draws operations.
	Bingo28Draws = bingo28DrawsDao{internal.NewBingo28DrawsDao()}
)

// Add your custom methods and functionality below.
