// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// bingoDynamicOddsDao is the data access object for the table game_bingo_dynamic_odds.
// You can define custom methods on it to extend its functionality as needed.
type bingoDynamicOddsDao struct {
	*internal.BingoDynamicOddsDao
}

var (
	// BingoDynamicOdds is a globally accessible object for table game_bingo_dynamic_odds operations.
	BingoDynamicOdds = bingoDynamicOddsDao{internal.NewBingoDynamicOddsDao()}
)

// Add your custom methods and functionality below.
