// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// bingoDrawsDao is the data access object for the table game_bingo_draws.
// You can define custom methods on it to extend its functionality as needed.
type bingoDrawsDao struct {
	*internal.BingoDrawsDao
}

var (
	// BingoDraws is a globally accessible object for table game_bingo_draws operations.
	BingoDraws = bingoDrawsDao{internal.NewBingoDrawsDao()}
)

// Add your custom methods and functionality below.
