// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// bingo28BetTypesDao is the data access object for the table game_bingo28_bet_types.
// You can define custom methods on it to extend its functionality as needed.
type bingo28BetTypesDao struct {
	*internal.Bingo28BetTypesDao
}

var (
	// Bingo28BetTypes is a globally accessible object for table game_bingo28_bet_types operations.
	Bingo28BetTypes = bingo28BetTypesDao{internal.NewBingo28BetTypesDao()}
)

// Add your custom methods and functionality below.
