// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// canada28BetsDao is the data access object for the table game_canada28_bets.
// You can define custom methods on it to extend its functionality as needed.
type canada28BetsDao struct {
	*internal.Canada28BetsDao
}

var (
	// Canada28Bets is a globally accessible object for table game_canada28_bets operations.
	Canada28Bets = canada28BetsDao{internal.NewCanada28BetsDao()}
)

// Add your custom methods and functionality below.
