// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// canada28BetTypesDao is the data access object for the table game_canada28_bet_types.
// You can define custom methods on it to extend its functionality as needed.
type canada28BetTypesDao struct {
	*internal.Canada28BetTypesDao
}

var (
	// Canada28BetTypes is a globally accessible object for table game_canada28_bet_types operations.
	Canada28BetTypes = canada28BetTypesDao{internal.NewCanada28BetTypesDao()}
)

// Add your custom methods and functionality below.
