// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// canada28DrawsDao is the data access object for the table game_canada28_draws.
// You can define custom methods on it to extend its functionality as needed.
type canada28DrawsDao struct {
	*internal.Canada28DrawsDao
}

var (
	// Canada28Draws is a globally accessible object for table game_canada28_draws operations.
	Canada28Draws = canada28DrawsDao{internal.NewCanada28DrawsDao()}
)

// Add your custom methods and functionality below.
