// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// canada28DynamicOddsDao is the data access object for the table game_canada28_dynamic_odds.
// You can define custom methods on it to extend its functionality as needed.
type canada28DynamicOddsDao struct {
	*internal.Canada28DynamicOddsDao
}

var (
	// Canada28DynamicOdds is a globally accessible object for table game_canada28_dynamic_odds operations.
	Canada28DynamicOdds = canada28DynamicOddsDao{internal.NewCanada28DynamicOddsDao()}
)

// Add your custom methods and functionality below.
