// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// customerServiceSessionDao is the data access object for the table game_customer_service_session.
// You can define custom methods on it to extend its functionality as needed.
type customerServiceSessionDao struct {
	*internal.CustomerServiceSessionDao
}

var (
	// CustomerServiceSession is a globally accessible object for table game_customer_service_session operations.
	CustomerServiceSession = customerServiceSessionDao{internal.NewCustomerServiceSessionDao()}
)

// Add your custom methods and functionality below.
