// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// customerServiceMessageDao is the data access object for the table game_customer_service_message.
// You can define custom methods on it to extend its functionality as needed.
type customerServiceMessageDao struct {
	*internal.CustomerServiceMessageDao
}

var (
	// CustomerServiceMessage is a globally accessible object for table game_customer_service_message operations.
	CustomerServiceMessage = customerServiceMessageDao{internal.NewCustomerServiceMessageDao()}
)

// Add your custom methods and functionality below.
