// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// errorLogDao is the data access object for the table game_error_log.
// You can define custom methods on it to extend its functionality as needed.
type errorLogDao struct {
	*internal.ErrorLogDao
}

var (
	// ErrorLog is a globally accessible object for table game_error_log operations.
	ErrorLog = errorLogDao{internal.NewErrorLogDao()}
)

// Add your custom methods and functionality below.
