// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// groupMessageDao is the data access object for the table game_group_message.
// You can define custom methods on it to extend its functionality as needed.
type groupMessageDao struct {
	*internal.GroupMessageDao
}

var (
	// GroupMessage is a globally accessible object for table game_group_message operations.
	GroupMessage = groupMessageDao{internal.NewGroupMessageDao()}
)

// Add your custom methods and functionality below.
