// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// kenoBetTypesDao is the data access object for the table game_keno_bet_types.
// You can define custom methods on it to extend its functionality as needed.
type kenoBetTypesDao struct {
	*internal.KenoBetTypesDao
}

var (
	// KenoBetTypes is a globally accessible object for table game_keno_bet_types operations.
	KenoBetTypes = kenoBetTypesDao{internal.NewKenoBetTypesDao()}
)

// Add your custom methods and functionality below.
