// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// kenoBetsDao is the data access object for the table game_keno_bets.
// You can define custom methods on it to extend its functionality as needed.
type kenoBetsDao struct {
	*internal.KenoBetsDao
}

var (
	// KenoBets is a globally accessible object for table game_keno_bets operations.
	KenoBets = kenoBetsDao{internal.NewKenoBetsDao()}
)

// Add your custom methods and functionality below.
