// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// kenoDrawsDao is the data access object for the table game_keno_draws.
// You can define custom methods on it to extend its functionality as needed.
type kenoDrawsDao struct {
	*internal.KenoDrawsDao
}

var (
	// KenoDraws is a globally accessible object for table game_keno_draws operations.
	KenoDraws = kenoDrawsDao{internal.NewKenoDrawsDao()}
)

// Add your custom methods and functionality below.
