// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// kenoDynamicOddsDao is the data access object for the table game_keno_dynamic_odds.
// You can define custom methods on it to extend its functionality as needed.
type kenoDynamicOddsDao struct {
	*internal.KenoDynamicOddsDao
}

var (
	// KenoDynamicOdds is a globally accessible object for table game_keno_dynamic_odds operations.
	KenoDynamicOdds = kenoDynamicOddsDao{internal.NewKenoDynamicOddsDao()}
)

// Add your custom methods and functionality below.
