// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// merchantDao is the data access object for the table game_merchant.
// You can define custom methods on it to extend its functionality as needed.
type merchantDao struct {
	*internal.MerchantDao
}

var (
	// Merchant is a globally accessible object for table game_merchant operations.
	Merchant = merchantDao{internal.NewMerchantDao()}
)

// Add your custom methods and functionality below.
