// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// paymentChannelDao is the data access object for the table game_payment_channel.
// You can define custom methods on it to extend its functionality as needed.
type paymentChannelDao struct {
	*internal.PaymentChannelDao
}

var (
	// PaymentChannel is a globally accessible object for table game_payment_channel operations.
	PaymentChannel = paymentChannelDao{internal.NewPaymentChannelDao()}
)

// Add your custom methods and functionality below.
