// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// userBalancesDao is the data access object for the table game_user_balances.
// You can define custom methods on it to extend its functionality as needed.
type userBalancesDao struct {
	*internal.UserBalancesDao
}

var (
	// UserBalances is a globally accessible object for table game_user_balances operations.
	UserBalances = userBalancesDao{internal.NewUserBalancesDao()}
)

// Add your custom methods and functionality below.
