// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// userFrozenBalancesDao is the data access object for the table game_user_frozen_balances.
// You can define custom methods on it to extend its functionality as needed.
type userFrozenBalancesDao struct {
	*internal.UserFrozenBalancesDao
}

var (
	// UserFrozenBalances is a globally accessible object for table game_user_frozen_balances operations.
	UserFrozenBalances = userFrozenBalancesDao{internal.NewUserFrozenBalancesDao()}
)

// Add your custom methods and functionality below.
